Add support for synchronouos render functions
zerodays/react-native-gen-ui pull request #13
Opened 2024-04-15 19:24 UTC by matejm

### Description of change

Fixes issue #12.

Why? Sometimes your tool simply displays some info and the requirement for async generators is irrelevant.

#### Discussion:

##### Should we also support synchronouos generators?

I think not as this could lead to tons of unexpected mistakes.

##### Should we also support async render functions without generators?

We have the capability to easily add the support, but maybe we should intentionally leave it out to actively encourage developers to use generators  to show current state of tool processing.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [ ] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2024-04-16 05:27 UTC, zigapk requested changes

2024-04-16 05:27 UTC, zigapk commented on README.md
> +If tool doesn't need to do any async operations as you expect the AI model to return all the required data to render the component, you can use a simple function that returns a component:
```suggestion
If tool doesn't need to do any async operations as you expect the AI model to return all the required data to render the component, you can use a simple function that returns the data and the component:
```

2024-04-16 05:32 UTC, zigapk commented
Great! I'd only suggest changing the documentation slightly.

2024-04-17 11:05 UTC, vucinatim approved these changes
Good addition! ✅

2024-04-17 11:10 UTC, merged